name: Go
on:
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12

    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: go/src/github.com/containerd/containerd
   
    - name: Install dev tools
      run: ./script/setup/install-dev-tools
      env:
        GOPATH: /home/runner/work/woodpecker/go

    - name: Check
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin # See https://github.com/actions/setup-go/issues/14
        make check
      env:
        GOPATH: /home/runner/work/woodpecker/go

    - name: Build
      run: make build
      env:
        GOPATH: /home/runner/work/woodpecker/go
